services:
  smart-attendance-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_attendance_app
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 512M
